# Generated by Django 2.1.7 on 2019-04-04 18:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190404_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/main'), upload_to=''),
        ),
    ]
