# Generated by Django 2.1.7 on 2019-04-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190405_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDecrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EncImage', models.ImageField(upload_to='encrypted_img/')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
